In [3]:
#importing Libraries 
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

c:\Users\vshru\AppData\Local\Programs\Python\Python314\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
#loading data
dataset = load_dataset('lukebarousse/data_jobs')
df =dataset['train'].to_pandas()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [ ]:
#Data Cleanup
df['job_posted_date']= pd.to_datetime(df['job_posted_date'])
df.info()

In [7]:
#Accessing rows and columns 
df.loc[:10,'salary_rate':'salary_hour_avg']

   salary_rate  salary_year_avg  salary_hour_avg
0          NaN              NaN              NaN
1          NaN              NaN              NaN
2          NaN              NaN              NaN
3          NaN              NaN              NaN
4          NaN              NaN              NaN
5          NaN              NaN              NaN
6          NaN              NaN              NaN
7          NaN              NaN              NaN
8          NaN              NaN              NaN
9          NaN              NaN              NaN
10         NaN              NaN              NaN

In [14]:
median_salary_year =df.salary_year_avg.median()
median_salary_hour = df.salary_hour_avg.median()

In [15]:
df_filled = df

In [16]:
df_filled['salary_year_avg']=df_filled.salary_year_avg.fillna(median_salary_year)

In [17]:
df_filled['salary_hour_avg']=df.salary_hour_avg.fillna(median_salary_hour)

In [18]:
df_filled.loc[:10,'salary_rate':'salary_hour_avg']

   salary_rate  salary_year_avg  salary_hour_avg
0          NaN         115000.0            45.98
1          NaN         115000.0            45.98
2          NaN         115000.0            45.98
3          NaN         115000.0            45.98
4          NaN         115000.0            45.98
5          NaN         115000.0            45.98
6          NaN         115000.0            45.98
7          NaN         115000.0            45.98
8          NaN         115000.0            45.98
9          NaN         115000.0            45.98
10         NaN         115000.0            45.98

In [24]:
df_unique = df_filled

In [27]:
df_unique =df_unique.drop_duplicates(subset =['job_title','company_name'] )
print('Length of original df:',len(df_filled))
print('Length of drop duplicates df:',len(df_unique))
print('Rows droped:',len(df_filled)-len(df_unique))

Length of original df: 785741
Length of drop duplicates df: 508042
Rows droped: 277699

In [28]:
id(df_unique)==id(df_filled)

False