Exercise - Investigate Trending Skills

In [1]:
#importing Libraries 
import ast
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

c:\Users\vshru\AppData\Local\Programs\Python\Python314\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
#loading data
dataset = load_dataset('lukebarousse/data_jobs')
df =dataset['train'].to_pandas()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
#Data Cleanup
df['job_posted_date']= pd.to_datetime(df['job_posted_date'])

In [4]:
df['job_skills'] = df['job_skills'].apply(lambda x:ast.literal_eval(x) if pd.notna(x)else x)

In [5]:
#creates a new dataframe with filtered column 
df_DA = df[df['job_title_short']=='Data Analyst'].copy()

In [7]:
#creates a new column in dataframe 
df_DA['job_posted_month_no'] = df_DA['job_posted_date'].dt.month

In [8]:
df_DA_explode = df_DA.explode('job_skills')

In [9]:
df_DA_explode

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month_no
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,r,"{'analyst_tools': ['power bi', 'tableau'], 'pr...",1
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,python,"{'analyst_tools': ['power bi', 'tableau'], 'pr...",1
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,sql,"{'analyst_tools': ['power bi', 'tableau'], 'pr...",1
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,nosql,"{'analyst_tools': ['power bi', 'tableau'], 'pr...",1
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,power bi,"{'analyst_tools': ['power bi', 'tableau'], 'pr...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785717,Data Analyst,Data & Analytics Architect (w/m/x),"Erfurt, Jerman",melalui LinkedIn,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,NTT DATA DACH,azure,"{'cloud': ['aws', 'azure']}",3
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,sas,"{'analyst_tools': ['sas', 'excel'], 'programmi...",3
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,sas,"{'analyst_tools': ['sas', 'excel'], 'programmi...",3
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,sql,"{'analyst_tools': ['sas', 'excel'], 'programmi...",3
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,excel,"{'analyst_tools': ['sas', 'excel'], 'programmi...",3

In [10]:
#Use pivot when you want to take values from a column and turn them into headers (columns). This "widens" your data.
df_DA_pivot =df_DA_explode.pivot_table(index = 'job_posted_month_no',columns='job_skills',aggfunc='size',fill_value=0)

In [11]:


df_DA_pivot.reset_index()

job_skills,job_posted_month_no,airflow,airtable,alteryx,angular,angular.js,ansible,apl,arch,asana,...,webex,windows,wire,word,workfront,wrike,wsl,xamarin,yarn,zoom
0,1,197,17,551,63,2,20,2,1,29,...,17,228,6,1778,0,11,6,0,9,95
1,2,169,2,448,49,0,14,1,4,27,...,9,202,6,1235,4,2,5,0,4,41
2,3,181,4,442,34,0,23,6,1,17,...,8,194,8,1203,1,1,3,1,5,45
3,4,155,4,413,22,0,11,8,9,9,...,9,185,14,1177,8,2,1,0,6,26
4,5,128,8,310,30,0,19,9,2,8,...,11,122,3,957,3,4,0,0,7,18
5,6,164,14,393,29,0,14,9,4,16,...,8,157,14,1237,6,6,0,0,11,34
6,7,207,4,366,15,0,8,5,8,19,...,5,161,11,1069,0,3,0,0,6,38
7,8,197,3,413,21,0,12,10,3,13,...,9,184,11,1298,0,1,0,0,11,41
8,9,118,4,317,21,0,14,3,10,12,...,4,150,8,945,0,1,0,0,5,25
9,10,173,11,350,40,0,19,0,8,11,...,4,156,8,990,5,2,0,1,4,39
10,11,169,7,293,24,0,19,0,5,4,...,4,144,4,887,1,1,1,0,6,26
11,12,144,10,274,28,0,13,0,8,11,...,6,139,8,786,3,5,0,0,2,37

In [ ]:
df_DA_pivot = df_DA_pivot.reset_index()
df_DA_pivot['job_posted_month'] = df_DA_pivot['job_posted_month_no'].apply(lambda x: pd.to_datetime(x, format='%m').strftime('%b'))
df_DA_pivot = df_DA_pivot.set_index('job_posted_month')
df_DA_pivot = df_DA_pivot.drop(columns='job_posted_month_no')

In [ ]:
df_DA_pivot.iloc[:,:5].plot(kind = 'line')

plt.title('Top 5 Skills for Data Analysts per Month')
plt.xlabel('')
plt.ylabel('Count')
plt.show()

In [ ]:
#loc creates a new row named total .This calculates the sum of every column in your DataFrame.
df_DA_pivot.loc['Total'] = df_DA_pivot.sum()

In [ ]:
#The .loc indexer is used to access a row by its label.
df_DA_pivot=df_DA_pivot[df_DA_pivot.loc['Total'].sort_values(ascending = False).index]

In [ ]:
df_DA_pivot

In [ ]:
df_DA_pivot = df_DA_pivot.drop('Total')

In [ ]:
df_DA_pivot

In [ ]:
#You are grabbing every row but only the first five columns of your pivot table.
df_DA_pivot.iloc[:,:5].plot(kind = 'line')

plt.title('Top 5 Skills for Data Analysts per Month')
plt.xlabel('')
plt.ylabel('Count')
plt.show()